# Site settings
title: My Dream
header-img: img/home-bg.jpg
email: 294597950@qq.com
copyright_name: xuwei/blog/First Blog
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://xuwei.com"

github_username:  wei294597950
email_username:  294597950@qq.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
